# **Project 5 : A secure Static Website hosted on VM, backed by "Infinite Cloud Storage"**

## **The Architecture Plan**
Required following :-
1. VPC :- Your private network
2. VM(e2-micro) :- Runs a simple web server
3. Cloud Storage :- Stores our files
4. Signed URL :- Generated by VM to give a user 5 minutes access to private files.

## **Step 1 : Network and VM setup**
1. create a VPC and subnet :-
   name : project-network
2. create a firewall rule :-
   port :- 80 (HTTP)  | port :- 22 (SSH)
3. Launch VM :-
   name : web-gateway
   region : us-central1
   machine type : e2-micro
   boot-disk : 30GB standard presistent disk
   API access : "Allow full access to all cloud APIs"

## **Step 2 : Prepare private vault or cloud storage**
1. Create bucket : vault-[any-name-here]
2. Region : us-central
3. Versioning : Turn it on 
4. Upload a file : Upload any image/pdf
5. Permission : keep bucket private not for "allUsers"


## **Step 3 : Turn VM into server**
1. SSH into our VM
2. Install **Ngnix** :- 
   sudo apt-get update
   sudo apt-get install ngnix -y
3. Verify it works :- Copy the external IP and paste it on browser, you will see welcome message


## **Step 4 : Signed URL integration**
We want our website provide a temporary link to the file we upload in bucket.
1. In the terminal of our VM, generate signed url for that using following command :-
```
gsutil signurl -d 5m /path/to/your/service-account-key.json gs://vault-[any-name-here]/file-name
```
or we can also use the default service account
```
gcloud storage sign-url gs://vault-[any-name-here]/file-name --duration=1m
```

## **Step 5 : Create Website Interface**
1. in SSH edit the index.html file 
   sudo nano /var/www/html/index.html
2. PASTE the following code by removing default one:-
```
<html>
<body>
    <h1>A PREMIUM PORTAL</h1>
    <p>This website is running on a free e2-micro VM.</p>
    <p>The link below is a <b>Signed URL</b>. It expires in 1 minutes!</p>
    <a href="[PASTE_SIGNED_URL_HERE]">Download Secret Asset</a>
</body>
</html>
```
3. Save and exit :- Ctrl+o and enter and ctrl+x


## **The actual video/file links are work in udemy or netflix , where site is public but the actual file are in "signed" so people can't steal the content**
